name: Lint

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  gofmt:
    name: Go fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Go fmt
        run: go fmt

      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after formatting. Run 'go fmt' command and commit."; exit 1)

  golangcilint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.1
          only-new-issues: true
          working-directory: .
